Documentar bill payments
modyo/modyo-docs pull request #483
Opened 2021-11-30 17:43 UTC by DGarzaLee

2021-11-30 19:24 UTC, jordana-simon requested changes
el widget linkeado debería ser el widget en el sitio en español para que aparezca en español y luego en transifex cambiar el link al de inglés para esta parte

2021-12-01 07:38 UTC, siddharta1337 approved these changes

2021-12-01 12:45 UTC, jordana-simon approved these changes

2021-12-01 12:53 UTC, pipemeyer approved these changes

2021-12-06 18:51 UTC, merged