MCE-343
modyo/modyo-docs pull request #577
Opened 2023-06-22 18:12 UTC by Suz4nn3

MCE-343 Agregue info de Mis Tareas (My Tasks) y corregí el documento, según el style guide.

2023-06-23 14:15 UTC, jordana-simon requested changes
Allí dejé comentarios en algunos puntos, solo cosas de forma, dobles espaciados en su mayoría

2023-06-23 14:15 UTC, jordana-simon commented on docs/es/platform/core/key-concepts.md
> +Esto es útil cuando se publicó algo por error y es necesario volver a alguna de las versiones estables.  Permitiendo el resolver los problemas que la versión con errores pudo haber tenido.
Doble espaciado antes de Permitiendo

2023-06-23 14:15 UTC, jordana-simon commented on docs/es/platform/core/key-concepts.md
> +Si un Administrador quiere tomar el control de una vista, deberá hacer click en el elemento en uso y en la pantalla siguiente, hacer click en el botón  **Tomar Control**.
Este quedó con doble espaciado antes de Tomar control

2023-06-23 14:15 UTC, jordana-simon commented on docs/es/platform/core/key-concepts.md
> +* **Salir del modo vista previa**:  Cierra el modo vista previa, eliminando la barra y manteniendo la pestaña en la URL actual del sitio.
Quedó con doble espaciado antes de Cierra

2023-06-23 19:07 UTC, jordana-simon requested changes
un pequeño error de tipeo

2023-06-23 19:07 UTC, jordana-simon commented on docs/es/platform/core/key-concepts.md
> +El modo vista previa te permite previsualizar los cambios relaizados a elementos publicables como las Entradas, Pages, Navigation, Widgets o Plantillas. El acceso a este modo está en la parte superio
realizados

2023-06-23 19:52 UTC, Suz4nn3 commented on docs/es/platform/core/key-concepts.md
> +El modo vista previa te permite previsualizar los cambios relaizados a elementos publicables como las Entradas, Pages, Navigation, Widgets o Plantillas. El acceso a este modo está en la parte superio
terrible error, que bueno que lo cachaste, gracias!!

2023-06-27 18:18 UTC, jordana-simon approved these changes

2023-06-28 19:54 UTC, siddharta1337 approved these changes

2023-07-03 19:57 UTC, merged