MCE-344-redirect-post-login
modyo/modyo-docs pull request #581
Opened 2023-06-30 20:50 UTC by Suz4nn3

Agregue información de redirección posterior a login

Corrección de estilo de todo el documento

Eliminé filtros avanzados en users (no existen)

Queda pendiente verificar si existe la opción de guardar un segmento después de filtrar usuarios.

2023-06-30 22:22 UTC, jordana-simon requested changes

2023-06-30 22:22 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +Asegúrate de incluir los códigos personalizables en cada correo, ya que estos códigos permiten que la plataforma incluya la información aleatoria del usuario al momento del envío.
No se si asegúrate está bien allí, porque se puede hacer o no.
Lo otro es la información "aleatoria"? esa sí que no creo

2023-06-30 22:22 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +Para  facilitar el acceso a la plataforma, puedes configurar el inicio de sesión y el registro a través de servicios estándar.
Quedó con doble espaciado entre Para y Facilitar

2023-06-30 22:22 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +Para eliminar a un administrador del reino, selecciona la casilla a la izquierda de su nombre y haz click en el botón **borrar** en la parte inferior.
**Borrar** con mayuscula?

2023-06-30 22:22 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +Las opciones disponibles al habilitar reCAPTCHA en el reino, son:
Yo se que esto viene de antes, pero en realidad no se si son opciones. La opción es habilitar y deshabilitar si lo habilitas tienes que llenar los dos otros.

2023-07-03 19:26 UTC, jordana-simon requested changes

2023-07-03 19:26 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +  - Habilitar confirmación de correo electrónico: Habilita un campo adicional de correo electrónico que el usuario debe rellenar y que debe coincidir con el campo primario de correo electrónico.
Aquí hay un espacio después del punto.

2023-07-03 19:26 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +En Modyo puedes personalizar la página de login a la que acceden tus usuarios una vez que ingresen a tu sitio.
Aquí hay un esapcio después del punto.

2023-07-03 19:26 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +7. Haz click en **Guardar**
ponemos punto al final de esto?

2023-07-03 19:26 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +8. Haz click en **Publicar**
Ponemos punto al final?

2023-07-03 19:26 UTC, jordana-simon commented on docs/es/platform/customers/realms.md
> +Puedes crear un máximo de 20 campos personalizados en cada reino.
Hay un espacio después del punto

2023-07-03 19:55 UTC, Suz4nn3 commented on docs/es/platform/customers/realms.md
> +7. Haz click en **Guardar**
y tambien al final de Publicar

2023-07-03 20:47 UTC, jordana-simon approved these changes

2023-07-04 19:55 UTC, merged