MCE-348 documentar grupos en tipos de contenido
modyo/modyo-docs pull request #590
Opened 2023-07-12 18:50 UTC by Suz4nn3

* Added groups
* Revised according to style guide

2023-07-12 22:14 UTC, jordana-simon requested changes

2023-07-12 22:14 UTC, jordana-simon commented on docs/es/platform/content/types.md
> +A los Tipos de Contenido se les puede asignar una cardinalidad. Esta variable indica  cuantas Entradas pueden existir para este Tipo. Puedes agregar idiomas al repositorio y generar Entradas en vario
despues de indica quedó con doble espaciado

2023-07-12 22:14 UTC, jordana-simon commented on docs/es/platform/content/types.md
> +El nombre del campo es de suma importancia, ya que será utilizado para acceder a su valor en los SDK de Liquid y JS.  Para acceder al valor de un campo de una entrada puedes utilizar la sintaxis <spa
Quedó con doble espaciado antes de Para

2023-07-12 22:14 UTC, jordana-simon commented on docs/es/platform/content/types.md
> +### Casilla
Está como checkbox en español en la plataforma

2023-07-12 22:14 UTC, jordana-simon commented on docs/es/platform/content/types.md
> +Utiliza este campo para ingresar un número decimal.  El número debe ser, forzosamente, entre `-65325` y `+65325`. Sin embargo, se puede acotar haciendo uso de las restricciones:
Doble espaciado antes de El

2023-07-12 22:14 UTC, jordana-simon commented on docs/es/platform/content/types.md
> +Utiliza este campo para ingresar un número decimal.  El número debe ser, forzosamente, entre `-65325` y `+65325`. Sin embargo, se puede acotar haciendo uso de las restricciones:
forzosamente a mi me suena extraño, obligatoriamente?

2023-07-13 16:54 UTC, jordana-simon approved these changes
Solo nos falta ver lo de la etiqueta coming soon

2023-07-13 19:24 UTC, Suz4nn3 commented on docs/es/platform/content/types.md
> +Los Tipos de contenido son la base para tus Entradas. Los Tipos definen qué campos y validaciones son requeridas para las Entradas, contando con más de 15 tipos de campos.
No, generalmente Tipos si la lleva porque empieza la oración. Solo Contenido no, porque en español lo correcto es no escribir tipo título, como en inglés, donde todas las palabras de los títulos llevan mayúscula.

2023-07-13 19:26 UTC, Suz4nn3 commented on docs/es/platform/content/types.md
> +A los Tipos de Contenido se les puede asignar una cardinalidad. Esta variable indica  cuantas Entradas pueden existir para este Tipo. Puedes agregar idiomas al repositorio y generar Entradas en vario
gracias!!

2023-07-13 19:44 UTC, merged