MCE-358 documentar space y site viewer
modyo/modyo-docs pull request #593
Opened 2023-07-13 22:20 UTC by Suz4nn3

Corrección de estilo y redacción

Adición de SIte viewer

Adición de Space viewer

2023-07-15 00:45 UTC, siddharta1337 requested changes

2023-07-15 00:45 UTC, siddharta1337 commented on docs/es/platform/core/roles.md
> +1. Desde Modyo Platformhaz click en **Configuración**
falto un espacio en "Platformhaz"

2023-07-15 00:45 UTC, siddharta1337 commented on docs/es/platform/core/roles.md
> +- **Realm User**: PEste rol puede añadir usuarios, crear, modificar y enviar a revisión campañas, formularios y segmentos.
se escapó la PEste ajajajaja

2023-07-16 14:26 UTC, Suz4nn3 commented on docs/es/platform/core/roles.md
> +- **Realm User**: PEste rol puede añadir usuarios, crear, modificar y enviar a revisión campañas, formularios y segmentos.
oh no!!! Arreglado, gracias!!

2023-07-17 14:05 UTC, siddharta1337 approved these changes

2023-07-17 14:17 UTC, jordana-simon approved these changes

2023-07-17 14:17 UTC, merged