Actualiza release notes para version 9.2.40
modyo/modyo-docs pull request #594
Opened 2023-07-14 19:53 UTC by tyanez-modyo

Actualiza release notes para version 9.2.40

2023-07-17 19:15 UTC, jordana-simon requested changes

2023-07-17 19:15 UTC, jordana-simon commented on docs/es/platform/release-notes.md
> +* Se valida correctamente el campo defaul email sender en las configuraciones del reino, ahora tampoco puede estar vacío.
default?

2023-07-17 20:14 UTC, Suz4nn3 commented on docs/es/platform/release-notes.md
> +* Rutas password y signup dejan de responder a  extensiones que no correspondan
Me parece que hay doble espacio entre "a" y "extensiones"

2023-07-19 16:13 UTC, jordana-simon approved these changes

2023-07-19 16:15 UTC, merged