MCE-372 buscador en sitios y revisión de doc
modyo/modyo-docs pull request #605
Opened 2023-08-08 20:10 UTC by Suz4nn3

Todo el documento de sitios está ya revisado, agregue imágenes y sustituí imágenes rotas. 

Además, ya está la parte de Search en el documento.

2023-08-08 20:44 UTC, siddharta1337 commented on docs/es/platform/channels/sites.md
> +1. Da click en tu sitio.
Esto es solo un comentario: atención a la consistencia, si usamos "Da" en vez de "Haz" . En el resto del documento usamos "Haz".

 tratemos de mantener cierto nivel de consistencia, no digo que reemplacemos todo, pero seria util si tenemos un guideline sobre esto que se usa muchisimo en todos los materiales que producimos.

2023-08-08 20:44 UTC, siddharta1337 commented on docs/es/platform/channels/sites.md
> +1. En la ventana emergente verás todos los elementos con diferencias entre los stages seleccionados. Haz click en _Ver_ para obtener más detalles sobre los cambios.
la ventana que aparece??? dios, que se fumaron para escribir eso! good catch

2023-08-08 20:44 UTC, siddharta1337 commented on docs/es/platform/channels/sites.md
> +Cuando tienes más de un stage en tu sitio, la página de "Overview" muestra los detalles del stage actual y un botón para sincronizar cambios entre stages.
Veo en el documento que el nombre de elementos en pantalla aparece con **negritas** ,  aca lo veo entre comillas, no se si me perdi de algo, pero te lo pongo en el radar.

2023-08-08 20:54 UTC, jordana-simon requested changes

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +- **Borrar**:  Eliminar definitivamente un sitio y todo sus elementos.
Quedó con doble espacio antes de Eliminar

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +::: tip Tip
no tebería haber espacio entre los ::: y tip

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +- Si el sitio es privado: Solo los usuarios con una sesión de Modyo pueden ver el sitio.
Sobra un espacio después del punto

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +- Habilitar búsqueda: Si marcas esta opción, habilitas la función de búsqueda en el sitio.
Creo que sería bueno decir que al habilitar la búsqueda también se va a permitir la búsqueda desde los otros sitios si se usa el multi, tal vez un tip?

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +También conocido como SEO en-sitio y fuera-de-sitio, se refieren a las acciones que se pueden tomar dentro o fuera de una página para aumentar la visibilidad de tu sitio para los motores de búsqueda.
Esto quedó extraño para obtener mejores resultados para obtener un mejor poscicionamiento

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +- Al utilizar stages, los PWAs y redirecciones personalizadas serán deshabilitadas. Solo puedes hacer uso de PWAs y redirecciones personalizadas en el stage `main`.
las PWAs

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +Al hacer click en **Sincronizar**, puedes seleccionar qué cambios tomar de un stage. Si quieres sincronizar  cambios a `main`, debes estar en `main` al hacer click en **Sincronizar**.
Esto creo que puede confundir, porque no es que selecciones qué cambios, todos los cambios van a ir. Más bien es desde qué stage vas a traer los cambios

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +En el listado aparecen todos los elementos que tienen cambios pendientes por publicar. Si un elemento no aparece en el listado, es porque aún no tiene cambios por publicar.
Este warning no es de la revisión en equipo, es de la publicación conjunta.

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +- **Developer** :Este usuario está a cargo del desarrollo estructural de los recursos. Puede crear, modificar y enviar a revisión páginas, widgets, el menú y los templates. Todas las acciones realiza
Aquí nos falta el rol de viewer

2023-08-08 20:54 UTC, jordana-simon commented on docs/es/platform/channels/sites.md
> +Además de crear redirecciones una por una, puedes importar un [archivo CSV](/assets/examples/custom-redirections.csv) con hasta 1,000 redirecciones.
1000? 1.000? 1,000?

2023-08-09 01:03 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +1. Da click en tu sitio.
Ok, ahorita ajusto a Haz. 

Yo habia dejado ambas porque son sinónimos y asi evitamos repetir la misma palabra varias veces en un solo proceso.

2023-08-09 01:05 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +Cuando tienes más de un stage en tu sitio, la página de "Overview" muestra los detalles del stage actual y un botón para sincronizar cambios entre stages.
Si es un error mio, gracias por cacharlo!!

2023-08-09 01:07 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- Habilitar búsqueda: Si marcas esta opción, habilitas la función de búsqueda en el sitio.
Me gusta!!

2023-08-09 01:24 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +Además de crear redirecciones una por una, puedes importar un [archivo CSV](/assets/examples/custom-redirections.csv) con hasta 1,000 redirecciones.
![image](https://github.com/modyo/modyo-docs/assets/28905225/2b1ce887-f35c-4f0f-b032-c05dec743a53)


Según, lo correcto es 1 000

2023-08-09 22:12 UTC, jordana-simon requested changes

2023-08-09 22:13 UTC, btapia requested changes

2023-08-09 22:13 UTC, btapia commented on docs/es/platform/channels/sites.md
> +- **Developer** :Este usuario está a cargo del desarrollo estructural de los recursos. Puede crear, modificar y enviar a revisión páginas, widgets, el menú y los templates. Todas las acciones realiza
```suggestion
- **Developer**: Este usuario está a cargo del desarrollo estructural de los recursos. Puede crear, modificar y enviar a revisión páginas, widgets, menús y plantillas. Todas las acciones realizadas por un Developer deben pasar por un proceso de revisión antes de su publicación. Este rol no tiene permisos para publicar, eliminar o realizar _rollback_ a versiones anteriores de los recursos, ni tampoco para modificar la configuración del sitio. Existe una variante de este rol llamada Developer CLI, que además de los permisos de un Developer, permite actualizar widgets desde aplicaciones externas, como el [modyo-cli](/es/platform/channels/widgets.html#modyo-cli).
```

2023-08-09 22:13 UTC, btapia commented on docs/es/platform/channels/sites.md
> +- **Reviewer**: Este rol permite corregir y aprobar o desechar el trabajo realizado por los Developers. Puede crear, modificar, enviar a revisión y aprobar páginas, widgets, el menú y los templates.
```suggestion
- **Reviewer**: Este rol permite corregir, aprobar o desechar el trabajo realizado por los Developers. Puede crear, modificar, enviar a revisión y aprobar páginas, widgets, menús y plantillas. También puede publicar cuando se cumplen las condiciones de revisión. No puede editar la configuración del sitio.
```

2023-08-09 22:13 UTC, btapia commented on docs/es/platform/channels/sites.md
> +- **Admin**: El Administrador del sitio posee los mismos privilegios que los roles anteriores y tiene la capacidad de configurar todo el sitio. Esto incluye la creación, modificación, envío a revisió
La última parte no se entiende bien, ¿qué diferencia se quiere marcar con el rol de nivel de cuenta? Quizás debiésemos omitir esto para evitar confusiones:

"_Se diferencia del Default Admin, ya que un Site Admin puede configurar el sitio externo, pero no tiene la capacidad de realizar cambios en la plataforma en sí._"

cc @jordana-simon

2023-08-10 17:49 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +Si tienes instalado el último tema disponible y aún no cuentas con estos snippets, dirigirte a la sección "Temas" en la parte superior derecha y haz click en la opción "Cargar templates" de las opcio
Gracias!! 

Quito por completo el tip o solo el último párrafo?

2023-08-10 17:51 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +:::
Perdon, no me queda claro si debo eliminar o modificar esta línea.

2023-08-10 20:44 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> + - test.modyo.com/miSitio/search.json
si, excelente!!

2023-08-10 20:45 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- **Zona Horaria**: La zona horaria en que se muestran los campos de fecha y hora dentro del sitio. Esta configuración afecta a todas las secciones del sitio, incluyendo Pages, Navigation y Plantilla
gracias!!

2023-08-10 20:52 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- Redirigir a home cuando no se encuentra una URL: Por defecto, el sitio muestra una respuesta 404 (página no encontrada) cuando se accede a una URL que no existe. Sin embargo, si marcas esta opción,
Excelente recomendacion, gracias!

2023-08-10 20:56 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- **Activar dominios personalizados**:Al activar esta opción, puedes tener sitios con URLs personalizadas o "custom host" dentro del dominio.
que buen ojo!!

2023-08-10 21:05 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- **Developer** :Este usuario está a cargo del desarrollo estructural de los recursos. Puede crear, modificar y enviar a revisión páginas, widgets, el menú y los templates. Todas las acciones realiza
super!! Gracias!

2023-08-10 21:07 UTC, Suz4nn3 commented on docs/es/platform/channels/sites.md
> +- **Admin**: El Administrador del sitio posee los mismos privilegios que los roles anteriores y tiene la capacidad de configurar todo el sitio. Esto incluye la creación, modificación, envío a revisió
Estoy de acuerdo, lo estoy quitando, pero si quieren que lo regrese, solo avisenme :)

2023-08-11 04:00 UTC, btapia commented on docs/es/platform/channels/sites.md
> +Si tienes instalado el último tema disponible y aún no cuentas con estos snippets, dirigirte a la sección "Temas" en la parte superior derecha y haz click en la opción "Cargar templates" de las opcio
Se debe eliminar el tip completo.

2023-08-11 04:01 UTC, btapia commented on docs/es/platform/channels/sites.md
> +:::
La marqué para eliminación completa pues es la continuación del tip.

2023-08-11 04:02 UTC, btapia commented on docs/es/platform/channels/sites.md
> +:::
La marqué para eliminación pues es la continuación del tip.

2023-08-11 15:23 UTC, jordana-simon approved these changes

2023-08-11 15:56 UTC, btapia approved these changes

2023-08-11 19:36 UTC, merged