391 Sitio Privado - arquitectura
modyo/modyo-docs pull request #614
Opened 2023-08-30 10:09 UTC by Suz4nn3

correciones a documento

2023-08-30 18:33 UTC, jordana-simon requested changes

2023-08-30 18:33 UTC, jordana-simon commented on docs/es/architecture/patterns/private-site.md
> +- Carteras digitales
Dejemos Billetera digital por favor

2023-08-30 18:33 UTC, jordana-simon commented on docs/es/architecture/patterns/private-site.md
> +La implementación de sitios privados en Modyo es uno de los casos de uso más completos que se pueden trabajar en la plataforma. Esta implementación incluye herramientas para resolver tareas comunes,
quedó con doble espaciado antes de "mensajería, notificaciones"

2023-08-31 13:28 UTC, jordana-simon approved these changes

2023-08-31 13:50 UTC, siddharta1337 approved these changes

2023-08-31 15:10 UTC, merged