391 cambio a subtitulo sitio privado
modyo/modyo-docs pull request #617
Opened 2023-08-31 16:21 UTC by Suz4nn3

2023-08-31 16:23 UTC, jordana-simon commented on docs/es/architecture/patterns/private-site.md
> +<h3><a href="#Implementación de sitios privados en Modyo">#</a> Implementación de sitios privados en Modyo</h3>
El href tiene que quedar con guiones sino no va a funcionar la url

2023-08-31 16:27 UTC, Suz4nn3 commented on docs/es/architecture/patterns/private-site.md
> +<h3><a href="#Implementación de sitios privados en Modyo">#</a> Implementación de sitios privados en Modyo</h3>
gracias, corregido!

2023-08-31 20:51 UTC, jordana-simon requested changes

2023-08-31 20:51 UTC, jordana-simon commented on docs/es/architecture/patterns/private-site.md
> +<h3><a href="#Implementación-de-sitios-privados-en-Modyo">#</a> Implementación de sitios privados en Modyo</h3>
perdón! dejemoslo sin mayúsculas también por fis

2023-08-31 20:51 UTC, jordana-simon commented on docs/es/architecture/patterns/private-site.md
> +<h3><a href="#Implementación-de-sitios-privados-en-Modyo">#</a> Implementación de sitios privados en Modyo</h3>
el href

2023-08-31 23:25 UTC, Suz4nn3 commented on docs/es/architecture/patterns/private-site.md
> +<h3><a href="#Implementación-de-sitios-privados-en-Modyo">#</a> Implementación de sitios privados en Modyo</h3>
también quite la tilde, esta bien?

2023-09-01 02:59 UTC, siddharta1337 approved these changes

2023-09-01 08:40 UTC, merged