398 microservicios
modyo/modyo-docs pull request #621
Opened 2023-09-04 10:42 UTC by Suz4nn3

2023-09-05 17:14 UTC, jordana-simon requested changes

2023-09-05 17:14 UTC, jordana-simon commented on docs/es/architecture/patterns/microservice.md
> +- **Eficiencia:** Traer unicamente la información requerida de la base de datos. En ocasiones puede ser beneficiosos utilizar [lazy loading](https://www.baeldung.com/hibernate-lazy-eager-loading) par
únicamente con tilde?

2023-09-05 17:14 UTC, jordana-simon commented on docs/es/architecture/patterns/microservice.md
> +- **Eficiencia:** Traer unicamente la información requerida de la base de datos. En ocasiones puede ser beneficiosos utilizar [lazy loading](https://www.baeldung.com/hibernate-lazy-eager-loading) par
consultas innecesarias (femenino)

2023-09-06 15:07 UTC, Suz4nn3 commented on docs/es/architecture/patterns/microservice.md
> +- **Resistencia:** La independencia del servicio aumenta la resistencia a los errores. En caso de existir un error en un servicio, las aplicaciones pueden degradar la funcionalidad sin afectar toda l
En la línea 38? Cambiar **Resistencia** por **Resilencia** ?

2023-09-06 19:03 UTC, jordana-simon approved these changes

2023-09-06 19:03 UTC, merged