393 SCIM
modyo/modyo-docs pull request #628
Opened 2023-09-09 15:28 UTC by Suz4nn3

2023-09-11 12:19 UTC, jordana-simon commented on docs/es/platform/core/integrations/scim.md
> +Esta integración de grupos y usuarios entre Modyo y Microsoft Azure Active Directory con la API SCIM de Modyo, simplifica la gestión de usuarios en diferentes sistemas y reduce errores, favoreciendo
Creo que esto no deja tan claro que se crean los grupos en Modyo, no se lo que opinen los demás. Tal vez deberíamos expliciatrlo un poco más

2023-09-11 16:30 UTC, siddharta1337 approved these changes

2023-09-21 18:35 UTC, mzunigal requested changes

2023-09-21 18:35 UTC, mzunigal commented on docs/es/platform/core/integrations/scim.md
> +- Eliminar usuarios en un sistema y desaprovisionarlos en todos.
estuve revisando el aprovisionamiento y la sincronización se realiza en una sola vía desde azure a modyo
por lo que declarar que se realiza un intercambio de datos sería incorrecto.  Propongo lo siguiente:
```suggestion
El sistema de gestión de identidades multidominio (SCIM) establece una comunicación estandarizada entre Modyo y Microsoft Azure para la sincronización datos de usuarios y grupos de forma automática, permitiéndote:
- Crear usuarios en Microsoft Azure y aprovisionarlos de forma automática en Modyo.
- Actualizar datos de usuario en Microsoft Azure y reflejar los cambios en Modyo.
- Eliminar usuarios en Microsoft Azure  y desaprovisionarlos en Modyo.
```
Quizas también reforzar con alguna nota que la sincronización es en una vía por lo que datos modificados en Modyo no alteraran los datos de l usuario en Azure, y que esos cambios pueden ser alterados si alguna modificación de ese usario es realizada en Azure

2023-09-21 18:35 UTC, mzunigal commented on docs/es/platform/core/integrations/scim.md
> +Esta tarea se ejecuta cada 45 minutos, por lo que debes esperar este tiempo para ver los cambios reflejados en la plataforma.
Ahora en azure indica que el tiempo es de 40 minutos
```suggestion
Esta tarea se ejecuta cada 40 minutos, por lo que debes esperar este tiempo para ver los cambios reflejados en la plataforma.
```

2023-09-22 14:13 UTC, jordana-simon approved these changes

2023-09-22 18:09 UTC, merged