mejoras SAML
modyo/modyo-docs pull request #629
Opened 2023-09-11 19:36 UTC by Suz4nn3

2023-09-13 18:09 UTC, jordana-simon requested changes

2023-09-13 18:09 UTC, jordana-simon commented on docs/es/platform/core/integrations/identity-providers.md
> +Para lograr una conexión exitosa entre SAML y la Modyo, debes configurar los siguientes atributos en el Proveedor de Identidad:
y la Moydo?! y la plataforma Modyo o y Modyo

2023-09-14 07:40 UTC, Suz4nn3 commented on docs/es/platform/core/integrations/identity-providers.md
> +Para lograr una conexión exitosa entre SAML y la Modyo, debes configurar los siguientes atributos en el Proveedor de Identidad:
>face palm< sorry!!

2023-09-20 14:23 UTC, jordana-simon approved these changes

2023-09-20 15:33 UTC, mzunigal commented on docs/es/platform/core/integrations/identity-providers.md
> +- **IDP SSO del URL destino**: La URL a la cual se envía la solicitud de autenticación. Esto está en el proveedor de identidad.
```suggestion
- **IDP SSO del URL destino**: La URL a la cual se envía la solicitud de autenticación. Esto lo puedes encontrar en el proveedor de identidad.
```

2023-09-21 17:53 UTC, mzunigal approved these changes

2023-09-21 18:07 UTC, merged