418 BFF
modyo/modyo-docs pull request #631
Opened 2023-09-18 18:30 UTC by Suz4nn3

2023-09-19 17:08 UTC, siddharta1337 requested changes

2023-09-19 17:08 UTC, siddharta1337 commented on docs/es/architecture/patterns/bff.md
> +La arquitectura de Modyo enfatiza el desacoplamiento de capas frontend y backend.
esto está correcto, peeero, me da como una sensacion que lo que dice es que en el frontend y en el backend existen  una serie de capas ( como la cebolla de Shrek  🤣 ) en cada uno de ellos que puedo  llegar a desacoplar y eso esta tecnicamente incorrecto.

como contexto El objetivo de la frase es decir que existen dos capas: la de frontend y la de backend y que la arquitectura de modyo se enfatiza en que esas 2 capas estén desacopladas.

2023-09-19 20:03 UTC, Suz4nn3 commented on docs/es/architecture/patterns/bff.md
> +El patrón de arquitectura "Backend for Frontend" (BFF) es un enfoque que optimiza y adapta el backend de una aplicación a las necesidades específicas de sus clientes o a las interfaces front end de u
Gracias !! 

Como ves esta redacción: 

El patrón de arquitectura Backend for Frontend (BFF) es un enfoque que optimiza y adapta el backend de una aplicación a las necesidades específicas de las interfaces de usuario (UI).

2023-09-19 20:05 UTC, Suz4nn3 commented on docs/es/architecture/patterns/bff.md
> +La arquitectura de Modyo enfatiza el desacoplamiento de capas frontend y backend.
Shrek!!! 

Así mejor? 

La arquitectura de Modyo enfatiza que las capas de frontend y backend esten desacopladas. De esta formula, las APIs son independientes y pueden desplegarse en diferentes infraestructuras, conectándose mediante HTTP.

2023-09-20 18:56 UTC, jordana-simon approved these changes

2023-09-20 19:35 UTC, siddharta1337 commented on docs/es/architecture/patterns/bff.md
> +La arquitectura de Modyo enfatiza el desacoplamiento de capas frontend y backend.
@Suz4nn3  Perfecto!

2023-09-20 19:36 UTC, siddharta1337 commented on docs/es/architecture/patterns/bff.md
> +El patrón de arquitectura "Backend for Frontend" (BFF) es un enfoque que optimiza y adapta el backend de una aplicación a las necesidades específicas de sus clientes o a las interfaces front end de u
@Suz4nn3  Buenisimo!

2023-09-21 18:12 UTC, merged