MCE-399 remover svg de la documentacion
modyo/modyo-docs pull request #632
Opened 2023-09-19 20:23 UTC by siddharta1337

Elimina todas las apariciones de etiquetas SVG en la documentación.

Jira: https://modyohq.atlassian.net/browse/MCE-399

2023-09-19 20:31 UTC, siddharta1337 commented
@Suz4nn3  por favor toma este branch e incluye en este mismo PR cualquier cambio de texto que consideres necesario.

2023-09-19 22:07 UTC, Suz4nn3 reviewed
Ya agregué mis cambios.

2023-09-20 14:21 UTC, siddharta1337 commented
No puedo dejar 👍 porque yo generé el PR, pero por mi parte todo esta perfect.

2023-09-20 19:03 UTC, jordana-simon requested changes

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/templates.md
>  - **Aprobado**: Cuando se habilita la [revisión en equipo](/es/platform/core/key-concepts.html) y si es que se cumplieron las condiciones de revisión del elemento. Si estás en este estado, tus planti
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/templates.md
> +**Vista previa**: Da click en este icono para abrir una nueva pestaña con el modo de vista previa de las plantillas. En esta vista puedes ver todos los cambios en tus plantillas, como si estuvieran p
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/templates.md
> +**Diferencias**: Te lleva a la [vista de diferencias](/es/platform/channels/sites.html#revision-y-publicacion-conjunta), en la cual puedes comparar los cambios que hay entre múltiples versiones de tu
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/templates.md
>  * **Home**: Se usa exclusivamente en la página home del sitio.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +- **Aprobado**: Este estado aparece cuando esté habilitada la [revisión en equipo](/es/platform/core/key-concepts.html) y se cumplen las condiciones de revisión del elemento. Si está en este estado,
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +**Vista previa**: Abre en una nueva pestaña la vista previa de la versión editable del widget.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +**Diferencias**: Te lleva a la [vista de diferencias](/es/platform/core/key-concepts.html), en la cual puedes comparar los cambios que hay entre múltiples versiones del widget.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +**Otras opciones**: Permite archivar y crear una copia del widget actual.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +- **Publicar**: Te lleva a la vista de [publicación conjunta](/es/platform/core/key-concepts.html#revision-y-publicacion-conjunta) donde puedes publicar tus widgets.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +- **Forzar publicación**: Si eres administrador del sitio, puedes utilizar esta opción para publicar inmediatamente un widget, incluso si está habilitada la Revisión en Equipo.
los ":" en los asteriscos

2023-09-20 19:03 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
>  - **Páginas que usan este widget**: Verás un listado de páginas que están usando este widget. Mientras veas páginas en este listado, no podrás despublicar ni archivar el widget.
los ":" en los asteriscos

2023-09-20 21:46 UTC, jordana-simon approved these changes

2023-09-20 21:47 UTC, Suz4nn3 approved these changes

2023-09-20 21:48 UTC, merged