414 agregar entry excerpt
modyo/modyo-docs pull request #635
Opened 2023-09-20 20:46 UTC by Suz4nn3

2023-09-20 21:49 UTC, jordana-simon requested changes

2023-09-20 21:49 UTC, jordana-simon commented on docs/es/platform/channels/drops.md
> +| **entry.excerpt** El excerpt asociado a la página. | ```Este es el excerpt de un entry muy cool``` |
de una entry, porque le decimos la entry en femenino en todo el documento

2023-09-21 15:45 UTC, siddharta1337 approved these changes
Verificado el uso de `entry.excerpt` dentro de un sitio.

2023-09-22 13:14 UTC, jordana-simon approved these changes

2023-09-22 17:32 UTC, merged