431 Primeros Pasos
modyo/modyo-docs pull request #643
Opened 2023-09-26 15:13 UTC by Suz4nn3

2023-09-26 15:43 UTC, jordana-simon requested changes

2023-09-26 15:43 UTC, jordana-simon commented on docs/es/dynamic/README.md
> +Para comunicarte con el equipo, reportar un problema o sugerir una funcionalidad, puedes hacerlo a través de nuestro  [Centro de Soporte de Modyo](https://support.modyo.com).
Quedó con doble espacio antes de Centro de Soporte

2023-09-27 15:13 UTC, jordana-simon approved these changes

2023-09-29 00:51 UTC, siddharta1337 requested changes

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Bienvenido a la documentación oficial de [Dynamic Framework](https://dynamicframework.dev). En esta guía encontrarás información sobre las diversas características de este framework, así como definic
recomiendo `Te damos la bienvenida` o cualquier otra expresion con genero neutro. Es bueno usarlas siempre que se pueda pero tiene peso extra cuando la primera frase que le damos al usuario asumime que tiene que ser hombre para llegar alli.

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Si no tienes instalado el CLI de Modyo, se te preguntará si quieres instalarlo:
Esta parte se presta para que alguien que esta haciendo el tutorial con prisa y sin leer se confunda pensando que tiene que usar el comando ` @modyo/cli@3.3.0` 

Sugiero eliminar  el todo este texto:
```shell
Need to install the following packages:
  @modyo/cli@3.3.0
```
y reformular la linea 53 a algo como"

"Si no tienes instalado el CLI de Modyo, el sistema solicitará instalarlo porque es un paquete requerido, puedes encontrar las instrucciones de instalación del CLI en la [documentación oficial](https://docs.modyo.com/es/platform/channels/cli.html#modyo-cli)"

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Una vez instalado, se descarga la plantilla dynamic-react-base-template. Ahora, instala las dependencias y levanta el proyecto:
para refactorizar el texto siguendo la linea de la sugerencia anterior, aqui seria mejor algo como

"Este proceso descarga la plantilla dynamic-react-base-template. El siguiente paso es ingresar a la carpeta del proyecto para instalar dependencias y levantar el proyecto:"

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Usa un editor de código para explorar el código y ver por ti mismo cómo se utilizan los diferentes [componentes](/es/dynamic/ui/components) del sistema de diseño.
redundante. mejor usar:

" Usa un editor de código para explorar el proyecto y examinar cómo se utilizan ..."

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Para crear manualmente un nuevo proyecto con Dynamic Framework o agregarlo a un proyecto React, instala los paquetes requeridos:
puede ser confuso para un developer novato.

Sugiero:
"[...] con Dynamic Framework o agregarlo como dependencia a un proyecto React existente, instala [...] "

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Para comunicarte con el equipo, reportar un problema o sugerir una funcionalidad, puedes hacerlo a través de nuestro [Centro de Soporte de Modyo](https://support.modyo.com).
"Para comunicarte con el equipo de desarrollo" , no vaya ser que llamen al de futbol! JAJAJAJAJA

2023-09-29 00:51 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +Las consultas y solicitudes de soporte se aplican exclusivamente a las plantillas y cómo se integran con la plataforma Modyo. Las modificaciones y el código personalizado desarrollado sobre ellas est
Esto ya es por puro extra que soy, se vale ignorarme.

en donde dice "Modyo te ofrece servicios profesionales de acompañamiento experto y apoyo a los clientes."
 se puede incluir un enlace a https://www.modyo.com/services ... solo para ver si pega el chile y se genera una venta, el profit de modyo es nuestro sueldo y mi chamaco cambia de ropa muy rapido ajajajaj

2023-09-29 00:55 UTC, siddharta1337 commented
FYI: todos los comandos que aparecen estan testeados y funcionan OK a la version actual de dynamic.

2023-09-29 18:29 UTC, Suz4nn3 commented on docs/es/dynamic/README.md
> +Bienvenido a la documentación oficial de [Dynamic Framework](https://dynamicframework.dev). En esta guía encontrarás información sobre las diversas características de este framework, así como definic
si!!  A mi tampoco me gusto empezar en masculino, pero no di con la introducción correcta, gracias!

2023-09-29 18:36 UTC, Suz4nn3 commented on docs/es/dynamic/README.md
> +Una vez instalado, se descarga la plantilla dynamic-react-base-template. Ahora, instala las dependencias y levanta el proyecto:
quedo así: 

Este proceso descarga la plantilla dynamic-react-base-template, una vez que tengas la plantilla, ingresa a la carpeta del proyecto para instalar las dependencias y levantar el proyecto:

esta correcto?

2023-09-29 18:38 UTC, Suz4nn3 commented on docs/es/dynamic/README.md
> +Para comunicarte con el equipo, reportar un problema o sugerir una funcionalidad, puedes hacerlo a través de nuestro [Centro de Soporte de Modyo](https://support.modyo.com).
hahahahah, gracias!!

2023-10-02 17:42 UTC, siddharta1337 approved these changes

2023-10-02 18:56 UTC, merged