419 sistema de diseno - arq
modyo/modyo-docs pull request #644
Opened 2023-09-27 21:14 UTC by Suz4nn3

2023-09-28 20:55 UTC, jordana-simon requested changes

2023-09-28 20:55 UTC, jordana-simon commented on docs/es/architecture/patterns/design-system.md
> +- **Consistencia**: Un sistema de diseño mantiene la consistencia en múltiples productos y plataformas al proporcionar un conjunto estándar de componentes y estilos.
en todo el documento

2023-09-28 21:45 UTC, Suz4nn3 commented on docs/es/architecture/patterns/design-system.md
> +- **Consistencia**: Un sistema de diseño mantiene la consistencia en múltiples productos y plataformas al proporcionar un conjunto estándar de componentes y estilos.
sorry, ya quedo

2023-09-29 14:55 UTC, jordana-simon approved these changes

2023-10-02 20:22 UTC, siddharta1337 requested changes

2023-10-02 20:22 UTC, siddharta1337 commented on docs/es/architecture/patterns/design-system.md
> +Los sistema de diseño puede incluir hojas de estilo, tipografías, iconos, librerías javascript y componentes web. Dependiendo de los artefactos que informan el sistema de diseño, existen dos implemen
se escapo un singular en `Los sistema de diseño` debe ser `sistemas`

2023-10-03 12:15 UTC, siddharta1337 approved these changes

2023-10-03 16:47 UTC, merged