438 PWA
modyo/modyo-docs pull request #648
Opened 2023-09-29 18:16 UTC by Suz4nn3

2023-10-02 14:21 UTC, jordana-simon requested changes

2023-10-02 17:40 UTC, siddharta1337 requested changes

2023-10-02 17:40 UTC, siddharta1337 commented on docs/es/architecture/patterns/pwa.md
> +- **Trabajadores de servicio:** Una tecnología que permite almacenar en caché de recursos, funcionar sin conexión y mejorar el rendimiento de una PWA. Aunque Apple ha introducido limitaciones en la e
El termino "Trabajadores de servicio" no debería traducirse, el nombre que se usa en la industria es `Service Workers`

2023-10-02 17:40 UTC, siddharta1337 commented on docs/es/architecture/patterns/pwa.md
> +- **Twitter Lite:** Una versión ligera de la aplicación de Twitter que está diseñada para ser rápida y eficiente en el consumo de datos. Ofrece una experiencia similar a la aplicación nativa, con car
Creo que aqui planificando al futuro, ya aplica mencionar brevemente que hablamos de la aplicación conocida como twitter:
"[...]Una versión ligera de la aplicación de X (antes conocida como twitter ) que está ..."

y como nota al pie, que horrible cambio para una app que tenia tan buen nombre T_T ojala que modyo nunca pase a llamarse "O"

2023-10-02 17:40 UTC, siddharta1337 commented on docs/es/architecture/patterns/pwa.md
> +Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo un [experto nuestro](https://modyo.com/services) podría asesorar o colaborar con tu desarrollo, no dudes en contacta
siento que `un [experto nuestro]` suena a un servicio de baja categoría, una única persona no puede generar un shell para un banco, esto lo hace un team. A mi me suena mejor hablar de "expertos"

pero es super subjetivo, lo dejo a tu criterio @Suz4nn3

2023-10-02 19:24 UTC, Suz4nn3 commented on docs/es/architecture/patterns/pwa.md
> +Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo un [experto nuestro](https://modyo.com/services) podría asesorar o colaborar con tu desarrollo, no dudes en contacta
Lo deje asi: 
Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo nuestro [equipos de expertos](https://modyo.com/services) puede asesorar o colaborar con tu **desarrollo, no dudes en contactar a un ejecutivo comercial o de clientes de Modyo.**

Pero creo que me gusta más: 

Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo nuestro [equipos de expertos](https://modyo.com/services) puede asesorar o colaborar con tu **desarrollo, no dudes en contactarnos.** 

Cual prefieres?

2023-10-02 22:53 UTC, jordana-simon approved these changes

2023-10-03 12:19 UTC, siddharta1337 commented on docs/es/architecture/patterns/pwa.md
> +Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo un [experto nuestro](https://modyo.com/services) podría asesorar o colaborar con tu desarrollo, no dudes en contacta
El segundo esta cool 🙌 , ojo que dice "nuestrO equipoS de expertos"

2023-10-03 17:56 UTC, Suz4nn3 commented on docs/es/architecture/patterns/pwa.md
> +Si deseas recibir más información acerca de esta técnica de empaquetamiento y cómo un [experto nuestro](https://modyo.com/services) podría asesorar o colaborar con tu desarrollo, no dudes en contacta
Que bueno que cachaste eso, gracias!!! Ya lo corrijo y dejo la segunda. Thanks!!

2023-10-04 00:41 UTC, siddharta1337 approved these changes

2023-10-04 17:02 UTC, merged