440 SSG
modyo/modyo-docs pull request #650
Opened 2023-10-02 19:45 UTC by Suz4nn3

2023-10-02 22:52 UTC, jordana-simon commented on docs/es/architecture/patterns/ssg.md
>  ### ¿Cómo se implementa SSG en Modyo?
Lo dejamos como pregunta?

2023-10-03 01:34 UTC, Suz4nn3 commented on docs/es/architecture/patterns/ssg.md
>  ### ¿Cómo se implementa SSG en Modyo?
sorry y gracias!

2023-10-03 12:11 UTC, jordana-simon approved these changes

2023-10-03 13:44 UTC, siddharta1337 requested changes

2023-10-03 13:44 UTC, siddharta1337 commented on docs/es/architecture/patterns/ssg.md
> +- **Mayor tiempo de compilación en proyectos grandes:** A medida que el proyecto crece en tamaño y complejidad, el tiempo necesario para compilar las páginas puede aumentar considerablemente, alentan
no estoy seguro del verbo "alentar" entiendo que en este contexto quiere decir "hacer mas lento" pero ni siquiera se si puede usarse asi.

Para evitar confusiones recomiendo una formula mas clara como "hacer mas lento" , "ralentizar"  o "reducir el rendimiento/velocidad"

2023-10-03 18:42 UTC, Suz4nn3 commented on docs/es/architecture/patterns/ssg.md
> +- **Mayor tiempo de compilación en proyectos grandes:** A medida que el proyecto crece en tamaño y complejidad, el tiempo necesario para compilar las páginas puede aumentar considerablemente, alentan
gracias!!  En México casi no se usa ralentizar, lo ves bien asi? 

A medida que el proyecto crece en tamaño y complejidad, el tiempo necesario para compilar las páginas puede aumentar considerablemente, haciendo más lento el flujo de trabajo de desarrollo; por lo que recomendamos una planificación adecuada para gestionar tiempos de compilación en proyectos más grandes.

2023-10-04 00:43 UTC, siddharta1337 commented on docs/es/architecture/patterns/ssg.md
> +- **Mayor tiempo de compilación en proyectos grandes:** A medida que el proyecto crece en tamaño y complejidad, el tiempo necesario para compilar las páginas puede aumentar considerablemente, alentan
Perfecto! Para hacer mas expedito el cambio incluyelo y asume mi like 👍 para hacer merge

2023-10-04 16:45 UTC, siddharta1337 approved these changes

2023-10-04 17:02 UTC, merged