corrrecion de documento
modyo/modyo-docs pull request #654
Opened 2023-10-05 18:34 UTC by Suz4nn3

2023-10-06 11:50 UTC, jordana-simon requested changes

2023-10-06 11:50 UTC, jordana-simon commented on docs/es/architecture/patterns/code-reuse.md
> +Si tienes alguna pregunta o requieres de soporte, no dudes en ponerte en contacto con nuestro [equipo de expertos](https://modyo.com/services).
linkemos a https://support.modyo.com/ por fis

2023-10-06 13:31 UTC, Suz4nn3 commented on docs/es/architecture/patterns/code-reuse.md
> +El reuso de código es la práctica de escribir código que puedes usar en múltiples contextos o aplicaciones, en lugar de crear código nuevo para cada función o aplicación nueva. El objetivo es "_escri
Yo también me lo cuestioné. Me gusta dejarlas porque es una frase muy usada en documentación también, pero no estoy segura. Prefieres solo comillas o como te gusta más?

2023-10-10 17:51 UTC, siddharta1337 commented on docs/es/architecture/patterns/code-reuse.md
> +Modyo ofrece diversas alternativas para reutilizar código que no implican el uso de Web Components. Dependiendo del tipo de proyecto en desarrollo, algunas de estas opciones pueden incluir:
Solo es un comentario de lector. Me surge la duda porque se mencionan aqui los web components??

No siento un contexto en el que sea necesario traerlos. No se si me esto perdiendo de algo pero veo que estamos hablandoespecificamente de reutilizacion de codigo y de pronto sale con esto de hacerlo **SIN** web components, para el caso tambien puede decir que modyo te permite reutilizar codigo que tampoco implica recordar los primeros 36 decimales de π pero porque rayos necesito que me digan eso? XD

2023-10-10 20:37 UTC, Suz4nn3 commented on docs/es/architecture/patterns/code-reuse.md
> +Modyo ofrece diversas alternativas para reutilizar código que no implican el uso de Web Components. Dependiendo del tipo de proyecto en desarrollo, algunas de estas opciones pueden incluir:
De acuerdo! Te late solo quitar ese punto o le hago algún otro ajuste?

2023-10-11 17:52 UTC, siddharta1337 approved these changes

2023-10-11 19:19 UTC, jordana-simon approved these changes

2023-10-11 19:57 UTC, merged