correcion de documento
modyo/modyo-docs pull request #655
Opened 2023-10-05 18:47 UTC by Suz4nn3

2023-10-05 21:33 UTC, jordana-simon requested changes

2023-10-05 21:33 UTC, jordana-simon commented on docs/es/architecture/patterns/ddd.md
> +El Domain-Driven Design (DDD) es una metodología de desarrollo de software que enfatiza la comprensión del dominio del negocio y modela el software según ese dominio. En DDD, los conceptos y estructu
enfatiza la comprensión o enfatiza en la comprensión?

2023-10-05 21:33 UTC, jordana-simon commented on docs/es/architecture/patterns/ddd.md
> +En el contexto de los micro frontends, puedes aplicar DDD al diseñar cada micro frontend para reflejar un subdominio específico del dominio del negocio. Por ejemplo, si estás construyendo un sitio we
puedes en lugar de popuedes

2023-10-06 20:10 UTC, Suz4nn3 commented on docs/es/architecture/patterns/ddd.md
> +El Domain-Driven Design (DDD) es una metodología de desarrollo de software que enfatiza la comprensión del dominio del negocio y modela el software según ese dominio. En DDD, los conceptos y estructu
Bard dice :laughing: : 

La forma correcta es "enfatiza la comprensión". La preposición "en" indica que la acción se realiza sobre la comprensión. En este caso, la acción es "enfatizar", que significa "dar importancia o relevancia". Por lo tanto, la frase "enfatiza la comprensión" significa "dar importancia o relevancia a la comprensión".

La forma "enfatiza la comprensión" también es más natural y fluida que la forma "enfatiza en la comprensión". La preposición "en" es más común que la preposición "en" en este contexto.

Sin embargo, ambas formas son gramaticalmente correctas. La forma "enfatiza en la comprensión" se puede utilizar en algunos casos, pero es menos común y puede sonar un poco extraña.

2023-10-10 16:13 UTC, siddharta1337 commented on docs/es/architecture/patterns/ddd.md
> +El Domain-Driven Design (DDD) es una metodología de desarrollo de software que enfatiza la comprensión del dominio del negocio y modela el software según ese dominio. En DDD, los conceptos y estructu
Paso a comentar para ver por donde nos vamos. Tomando en cuenta que el DDD se trata de entender lo que hace el negocio (esto es el Domain del domain driven design) para usarlo como una guia de diseño de software, yo lo formularía asi:

"El Domain-Driven Design (DDD) es una metodología de desarrollo de software que **se** enfatiza **en** la comprensión del dominio del negocio y modela el software según ese dominio." el resto, me hace perfecto sentido.

2023-10-10 20:42 UTC, Suz4nn3 commented on docs/es/architecture/patterns/ddd.md
> +- **Diseño de software de alta calidad:** Promueve principios sólidos de diseño de software, lo que conduce a un software más mantenible y adaptable.
Gracias @siddharta1337 !! 

Lo dejé asi, avísame si lo ven bien. 

- **Diseño de software de alta calidad:** Promueve los principios SOLID de diseño de software, lo que conlleva a un software más mantenible y adaptable.

2023-10-11 19:20 UTC, jordana-simon commented on docs/es/architecture/patterns/ddd.md
> +- **Diseño de software de alta calidad:** Promueve principios sólidos de diseño de software, lo que conduce a un software más mantenible y adaptable.
no XD a puro DDD

2023-10-11 19:21 UTC, jordana-simon approved these changes

2023-10-11 19:46 UTC, merged