MCE-475 errores 404
modyo/modyo-docs pull request #673
Opened 2023-10-13 21:50 UTC by siddharta1337

Esta tarea es para solucionar errores 404 que se encontraron en el scan ( ver mas detalles en Jira https://modyohq.atlassian.net/browse/MCE-475)

Por favor examinar los comentarios porque algunos cambios necesitan contexto.

2023-10-13 21:58 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +- [Plantillas de experiencias](/es/dynamic/experiences/retail/dashboard) financieras listas para descargar y modificar, con datos de ejemplo en APIs mocks.
la ruta `/es/dynamic/experiences` no existe, estoy moviendo esto a un componente especifico para mostrar una plantilla de experiencia financiera.

Soluciones alternativas:

- crear un archivo README.md en `dynamic/experiences`
- Eliminar esta linea si ya no aplica el enlace

2023-10-13 21:58 UTC, siddharta1337 commented on docs/es/dynamic/ui/README.md
> -Puedes acceder al Figma Kit de Dynamic Framework desde [el siguiente link](https://www.figma.com/community/file/1274095451173638903).
Eliminada esta línea porque el enlace esta muerto, se eliminó el figma kit y creo que no se publicará de nuevo.

2023-10-13 21:58 UTC, siddharta1337 commented on docs/es/platform/channels/navigation.md
> -Para más información de como se crea y publica un menú personalizado, ve [Creación de Mega Menú](/es/platform/tutorials/how-to-create-a-menu.html).
Este tutorial está desactualizado, en espera de dynamic para hacerlo con el framwork

2023-10-13 21:58 UTC, siddharta1337 commented on docs/es/platform/core/integrations/identity-providers.md
> +1. Desde la consola administrativa, por ejemplo `https://keycloak.example.com/auth/` haz click en agregar un nuevo realm.
Eliminado el formato de Link para que no genere un 404, ahora esta en vista de codigo.

2023-10-16 15:08 UTC, jordana-simon approved these changes

2023-10-16 17:15 UTC, Suz4nn3 approved these changes

2023-10-16 17:25 UTC, Suz4nn3 commented on docs/es/dynamic/ui/README.md
> -Puedes acceder al Figma Kit de Dynamic Framework desde [el siguiente link](https://www.figma.com/community/file/1274095451173638903).
Ojo, si se elimina el kit de figma, a lo mejor debemos considerar eliminar todo el apartado de Figma Kit

2023-10-16 17:27 UTC, Suz4nn3 requested changes

2023-10-16 17:27 UTC, Suz4nn3 commented on docs/es/dynamic/ui/README.md
> -Puedes acceder al Figma Kit de Dynamic Framework desde [el siguiente link](https://www.figma.com/community/file/1274095451173638903).
![image](https://github.com/modyo/modyo-docs/assets/28905225/a0de12a5-4469-4dbc-9bf8-986ff476b964)

2023-10-16 17:29 UTC, Suz4nn3 commented on docs/es/dynamic/README.md
> +- [Plantillas de experiencias](/es/dynamic/experiences/retail/dashboard) financieras listas para descargar y modificar, con datos de ejemplo en APIs mocks.
Pregunta, en la línea 22 se habla del kit de diseño, se refiere al Figma Kit que se eliminó?

2023-10-16 19:18 UTC, siddharta1337 commented on docs/es/dynamic/README.md
> +- [Plantillas de experiencias](/es/dynamic/experiences/retail/dashboard) financieras listas para descargar y modificar, con datos de ejemplo en APIs mocks.
Creo que lo mejor seria eliminar esto del todo y esperar a ver si lo ponemos online de nuevo.

@jordana-simon  Cuentanos si deberiamos eliminar referencias a Figma

2023-10-18 17:04 UTC, siddharta1337 commented on docs/es/dynamic/ui/README.md
> -Puedes acceder al Figma Kit de Dynamic Framework desde [el siguiente link](https://www.figma.com/community/file/1274095451173638903).
@Suz4nn3  ya eliminé la referencia a figma Kit, me cuentas si esta todo OK o si falta algo más aqui

2023-10-18 18:06 UTC, merged