MCE-511 revision de todo el documento
modyo/modyo-docs pull request #697
Opened 2023-12-01 00:07 UTC by Suz4nn3

Hola!

Les dejo el documento ya trabajado, esperando sus comentarios. 

Linda noche!

2023-12-01 12:04 UTC, jordana-simon requested changes

2023-12-01 12:04 UTC, jordana-simon commented on docs/es/platform/channels/cli.md
> +El usuario dueño del token debe tener un rol de [site reviewer o admin](https://docs.modyo.com/es/platform/core/roles.html#roles) en el sitio en el cual estás desplegando el micro-frontend para que s
dejemos la URL relativa solo a partir el /es

2023-12-01 12:04 UTC, jordana-simon commented on docs/es/platform/channels/cli.md
> +Si has definido [variables](http://localhost:8080/es/platform/core/key-concepts.html#variables-globales) sus valores pueden ser especificados a nivel global o particular a cada instancia del microfro
dejemos las urls relativas a partir del /es y todos los links a es y no a las en.

2023-12-04 13:14 UTC, siddharta1337 commented on docs/es/platform/channels/cli.md
Este comando puede generar un error si el usuario no presta atencion.

en la linea 72 ese comando crea una carpeta llamada `my-project-name`

Para que el comando `npm install` funcione, antes debe ejecutarse:

`cd my-project-name`

Sugiero agregar ese comando antes de la linea 77 (recomendado) para que quede:

```sh
$ cd my-project-name
$ npm install
$ npm run start
```


 mencionar en la linea 74  que se debe abrir la carpeta del proyecto en la terminal

2023-12-04 14:28 UTC, Suz4nn3 commented on docs/es/platform/channels/cli.md
Gracias Carlos!!

2023-12-04 14:49 UTC, siddharta1337 approved these changes

2023-12-06 19:16 UTC, jordana-simon approved these changes

2023-12-06 22:39 UTC, merged