MCE-484 correcion y actualizacion para Modyo 10
modyo/modyo-docs pull request #699
Opened 2023-12-19 12:20 UTC by Suz4nn3

2023-12-19 12:22 UTC, Suz4nn3 commented
Hola, creo que ya quedo!! 

@jordana-simon quieres que incluya a Valeria (o alguien mas) como reviewer?

2023-12-22 14:44 UTC, siddharta1337 requested changes

2023-12-22 14:44 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
> +Modyo te proporciona un espacio que te permite cargar, organizar y gestionar tus archivos de forma simple y eficiente.
🚨Alerta de detalle menor:

el texto esta perfecto, pero tal vez tenga mas impacto algo como:

"El gestor de archivos es un espacio que te permite cargar, organizar y gestionar tus archivos de forma simple y eficiente."

Contexto: Recuerdo que parte del guideline de marketing es ponerse mas del lado del cliente y darle pertenencia a SU herramienta, cosas como "Modyo te da" o "nuestra herramienta te da" hacen que se sienta algo ajeno. Claramente en la documentación no siempre aplica este concepto pero el primer parrafo puede permitirse ser un poco mas cercano.

2023-12-22 14:44 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
> +El editor de imágenes de Modyo te permite realizar pequeños cambios a las imágenes para facilitar su manejo en la plataforma.Para ajustar las dimensiones de una imagen, sigue estos pasos:
creo que falta un espacio en el punto de:
"...plataforma.Para ajustar las dimensiones"

2023-12-22 14:44 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
> +::: warning Atención
@Suz4nn3  Creo que estoy equivocado, pero aviso igual, veo que los warnings/tips que se borran estan sin espacio `:::warning` y los que agregas estan con espacio `::: warning` no se cual es el correcto pero dejo la nota para que verifiques. Ignora este mensaje si el formato esta OK.

2023-12-23 17:08 UTC, Suz4nn3 commented on docs/es/platform/content/asset-manager.md
> +Modyo te proporciona un espacio que te permite cargar, organizar y gestionar tus archivos de forma simple y eficiente.
Me fascina el comentario, gracias!!

2023-12-23 17:15 UTC, Suz4nn3 commented on docs/es/platform/content/asset-manager.md
> +El editor de imágenes de Modyo te permite realizar pequeños cambios a las imágenes para facilitar su manejo en la plataforma.Para ajustar las dimensiones de una imagen, sigue estos pasos:
gracias!!!

2023-12-26 12:38 UTC, siddharta1337 approved these changes

2023-12-26 18:01 UTC, jordana-simon requested changes

2023-12-26 18:01 UTC, jordana-simon commented on docs/es/platform/content/asset-manager.md
> +1. Selecciona **Media** del listado.
hay que elegir el espacio antes de que aparezca media o no?

2023-12-26 18:14 UTC, Suz4nn3 commented on docs/es/platform/content/asset-manager.md
> +1. Selecciona **Media** del listado.
sii!! Ahorita lo corrijo, gracias!!

2023-12-26 19:27 UTC, siddharta1337 requested changes

2023-12-26 19:27 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
>  :::tip Tip
alerta: revisar consistencia de mensajes, aqui aparece `:::tip` SIN espacios

2023-12-26 19:27 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
> +::: tip Tip
alerta: revisar consistencia de mensajes, aqui aparece `::: tip` CON espacio

2024-01-03 19:19 UTC, siddharta1337 commented
Revisados ambos tips localmente y funcionan sin problema en español. Procedo a Merge porque el contenido esta OK

2024-01-03 19:20 UTC, merged