MCE-532 correccion documento espacios
modyo/modyo-docs pull request #723
Opened 2024-01-31 18:06 UTC by Suz4nn3

2024-02-01 16:37 UTC, siddharta1337 requested changes

2024-02-01 16:37 UTC, siddharta1337 commented on docs/es/platform/content/spaces.md
> +- **NO SSL:** Wildcards son permitidos, pero Modyo debe ser seguro por defecto.
Esta frase se presta para confusiones. Modyo la plataforma debe ser segura? debo habitar eso yo? no queda claro si se refiere a la marca Modyo, al sitio donde trabajas o al panel de control de Modyo.

Tambien da a entender que tengo control sobre la activacion de esa seguridad, donde y como puedo habilitarla?

2024-02-09 14:49 UTC, siddharta1337 approved these changes

2024-02-12 14:02 UTC, jordana-simon approved these changes

2024-02-12 20:09 UTC, merged