MCE-549 agregue variables globales y snippets globales en sidebar
modyo/modyo-docs pull request #734
Opened 2024-02-26 20:44 UTC by Suz4nn3

2024-02-26 20:58 UTC, siddharta1337 approved these changes

2024-02-26 20:59 UTC, siddharta1337 commented
Agrego el label `do not merge` porque todo esta OK, pero antes necesitamos el contenido de las nuevas secciones.

2024-02-26 21:53 UTC, Suz4nn3 commented
El contenido de snippets en nuevo, el de variables lo tome de aqui: [#](https://docs.modyo.com/es/platform/core/key-concepts.html#variables-globales). Solo lo copie, no esta editado. 

Con gusto lo reviso y reescribo, pero no se si es prioridad.

2024-03-01 02:29 UTC, siddharta1337 commented on docs/es/platform/channels/global-snippets.md
> +1. Selecciona el snippet que quieres usar. Los snippets globales siempre llevan `global/nombredelsnippet`.
@Suz4nn3 no se si "llevan" exprese bien el concepto de lo que ocurre aqui, tal vez algo como:

- Los snippets globales siempre incluyen `global/nombredelsnippet` en su ruta.

o

- Los snippets globales siempre usan la nomenclatura `global/nombredelsnippet`.

Cualquier cambio que elijas toma en cuenta que se menciona varias veces en el documento y requiere que lo incluyas (por ejemplo en la linea 53)

2024-03-01 18:07 UTC, Suz4nn3 commented on docs/es/platform/channels/global-snippets.md
> +1. Selecciona el snippet que quieres usar. Los snippets globales siempre llevan `global/nombredelsnippet`.
gracias!!!

2024-03-05 16:25 UTC, siddharta1337 approved these changes

2024-03-06 21:06 UTC, jordana-simon requested changes

2024-03-06 21:06 UTC, jordana-simon commented on docs/es/platform/channels/global-variables.md
> +Modyo te ofrece la funcionalidad de definir elementos de forma global y reutilizar en todos los sitios donde se utilice Liquid. Esto permite compartir, por ejemplo, un _snippet_ de código entre difer
no aconsejamos usarlos para snippets, por eso existen los snippets globales además de las variables

2024-03-12 12:26 UTC, siddharta1337 approved these changes

2024-04-01 12:20 UTC, jordana-simon approved these changes

2024-04-06 00:52 UTC, merged