MCE-548 redimensionado de imagenes (en widgets, pages, templates y me…
modyo/modyo-docs pull request #743
Opened 2024-03-12 21:12 UTC by Suz4nn3

…dia)

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/channels/pages.md
> +Es necesario que el CDN de tu cuenta este en la nube para que los cambios se reflejen de inmediato, de lo contrario deberás solicitar la invalidación de caché a Modyo.
... necesario que el CDN de tu cuenta esté en la nube ...

Faltó la tilde en "esté"

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/channels/templates.md
> +Además, Modyo convierte la imagen a formato webp con calidad lossless de compresión. Lo que genera imágenes más pequeñas, con tiempos de carga menores y sin perder calidad.
"Lo que genera imagenes más **livianas**, con tiempos..."

Livianas en vez de pequeñas porque la segunda implica una escala que es un resultado potencialmente indeseado.

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/channels/templates.md
> +Es necesario que el CDN de tu cuenta este en la nube para que los cambios se reflejen de inmediato, de lo contrario deberás solicitar la invalidación de caché a Modyo.
también falto la tilde en "esté"

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/channels/widgets.md
> +:::
"esté"

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/channels/widgets.md
> +Además, Modyo convierte la imagen a formato webp con calidad lossless de compresión. Lo que genera imágenes más pequeñas, con tiempos de carga menores y sin perder calidad.
usar "livianas" en vez de pequeñas

2024-03-14 17:41 UTC, siddharta1337 commented on docs/es/platform/content/asset-manager.md
> +- `asset_image: width: XXX, quality: XX, widths: ‘XXX, XXX, XXX, sizes: (min-width: XXXpx) XXXpx` adaptando los valores según tus necesidades para asegurar que la imagen se ajuste a las diferentes pa
atributo srcet venía con un enlace (en el doc de google drive)  a la documentación de HTML  ese atributo es poco conocido y se presta para confusiones, en ese documento se aclara que estamos haciendo y que formato se va a mostrar al final.

2024-03-14 21:47 UTC, Suz4nn3 commented on docs/es/platform/channels/templates.md
> +Además, Modyo convierte la imagen a formato webp con calidad lossless de compresión. Lo que genera imágenes más pequeñas, con tiempos de carga menores y sin perder calidad.
sip, gracias!!

2024-03-18 14:30 UTC, siddharta1337 approved these changes

2024-03-19 18:49 UTC, jordana-simon requested changes

2024-03-19 18:49 UTC, jordana-simon commented on docs/es/platform/channels/pages.md
> +Es necesario que el CDN de tu cuenta esté en la nube para que los cambios se reflejen de inmediato, de lo contrario deberás solicitar la invalidación de caché a Modyo.
a traves de un ticket y poner el link a zendesk https://support.modyo.com/hc/en-us

2024-03-19 18:49 UTC, jordana-simon commented on docs/es/platform/channels/templates.md
> +Es necesario que el CDN de tu cuenta esté en la nube para que los cambios se reflejen de inmediato, de lo contrario deberás solicitar la invalidación de caché a Modyo.
a traves de un ticket y poner el link a zendesk https://support.modyo.com/hc/en-us

2024-03-19 18:49 UTC, jordana-simon commented on docs/es/platform/channels/widgets.md
> +Es necesario que el CDN de tu cuenta esté en la nube para que los cambios se reflejen de inmediato, de lo contrario deberás solicitar la invalidación de caché a Modyo.
a traves de un ticket y poner el link a zendesk https://support.modyo.com/hc/en-us

2024-03-28 18:45 UTC, jordana-simon approved these changes

2024-03-29 10:14 UTC, merged